title:              BlogPosts  
email:              petr.hrobar@merck.com
description:        Mostly statistics/ML and programming
author:             Petr Hrobar
baseurl:            ""
url:                "https://petrhrobar.github.io"

# Social Profiles
twitter_username:   
github_username:    petrhrobar
facebook_username:  
instagram_username:  
linkedin_username: petr-hroba%C5%99-2418a1215

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge